---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/static-golang}

inputs:
- name: cf-resource
  path: gopath/src/github.com/crdant/cf-route-resource
- name: autopilot
  path: gopath/src/github.com/contraband/autopilot
- name: cf-cli

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/crdant/cf-route-resource/scripts/ci
