---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: git

inputs:
  - name: source
  - name: build

run:
  path: source/ci/tasks/assets.sh
  args: [
    --output-dir, build
  ]
