---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: git

outputs:
  - name: build

run:
  path: source/ci/tasks/assets.sh
  args: [
    --input-dir, cf-cli,
    --output-dir, build
  ]
