---
jobs:
- name: publish
  public: true
  serial: true
  plan:
  - get: source
    trigger: true
  - get: version
    params: { pre: rc }
  - task: build
    file: source/ci/tasks/build.yml
    params:
      packageName: ((git-username))/((resource-name))
  - task: assets
    file: source/ci/tasks/assets.yml
  - put: resource-image
    params:
      build: assets
  - put: version
    params: { bump: final }

resources:
- name: source
  type: git
  source:
    uri: ((git-server-base))/((git-username))/((resource-name))
    branch: ((git-branch))

- name: version
  type: semver
  source:
    driver: git
    branch: version
    file: version
    key: current-version
    initial_version: 0.1.0-rc.0
    uri: ((git-server-base))/((git-username))/((resource-name))
    username: ((git-username))
    password: ((git-password))
    git_user: ((git-author))

- name: resource-image
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/((resource-name))
